CREATE TABLE PRO
(
    PRO_NO INTEGER PRIMARY KEY,
    PRO_TITLE VARCHAR(200) DEFAULT 'No title' NOT NULL,
    PRO_SDATE DATE DEFAULT CURRENT_DATE NOT NULL,
    PRO_DURAT INTERVAL YEAR DEFAULT '1' NOT NULL,
    PRO_MNG INTEGER UNIQUE NOT NULL REFERENCES EMP ON DELETE NO ACTION,
    PRO_DESC CLOB(10)
);

CREATE TABLE EMP
(
    EMP_NO    INTEGER PRIMARY KEY,
    EMP_NAME  VARCHAR(20) DEFAULT 'Incognito' NOT NULL,
    EMP_BDATE DATE        DEFAULT NULL CHECK ( EMP_BDATE >= DATE('1917-10-24') ),
    EMP_SAL   INTEGER,
    DEPT_NO   INTEGER     DEFAULT NULL REFERENCES DEPT ON DELETE SET NULL,
    PRO_NO    INTEGER     DEFAULT NULL,

    FOREIGN KEY (PRO_NO) REFERENCES PRO (PRO_NO) ON DELETE SET NULL
);

CREATE TRIGGER PRO_EMP_NO
    BEFORE INSERT ON EMP
WHEN (SELECT COUNT (*) FROM EMP WHERE NEW.PRO_NO = PRO_NO) >= 50
BEGIN
    SELECT RAISE(FAIL, 'TOO MANY EMPLOYEES IN THE PROJECT');
END;

CREATE TABLE DEPT
(
    DEPT_NO INTEGER PRIMARY KEY,
    DEPT_EMP_NO INTEGER NO NULL CHECK (DEPT_EMP_NO BETWEEN 1 AND 100),
    DEPT_NAME VARCHAR(200) DEFAULT 'Nameless' NOT NULL,
    DEPT_TOTAL_SAL INTEGER DEFAULT 1000000.00 NOT NULL CHECK (DEPT.DEPT_TOTAL_SAL >= 100000.00),
    DEPT_MNG INTEGER DEFAULT NULL REFERENCES EMP ON DELETE SET NULL
);

CREATE TRIGGER DEPT_MNG_UNQ
    AFTER INSERT ON DEPT
WHEN NEW.DEPT_MNG IS NOT NULL AND (SELECT COUNT(*) FROM DEPT WHERE DEPT_MNG = NEW.DEPT_MNG) != 1
BEGIN
    SELECT RAISE(FAIL, 'MORE THAN 1 MANAGER IN THE DEPARTMENT');
END;

CREATE TRIGGER DEPT_EMP_NO_MATCH
    AFTER INSERT ON DEPT
WHEN NEW.DEPT_EMP_NO != (SELECT COUNT(*) FROM EMP WHERE DEPT_NO = NEW.DEPT_NO)
BEGIN
    SELECT RAISE(FAIL, 'DEPT_EMP_NO DOES NOT MATCH');
END;

CREATE TRIGGER DEPT_TOTAL_SAL
    AFTER INSERT ON DEPT
WHEN NEW.DEPT_TOTAL_SAL < (SELECT SUM(EMP_SAL) FROM EMP WHERE DEPT_NO = EMP.DEPT_NO)
BEGIN
    SELECT RAISE(FAIL, 'DEPT_TOTAL_SAL IS LOWER THAN SUM EMP_SAL');
END;
